version: '3.8'
services:
  svelte-app: #frontend
    image: frieden
    ports:
      - "3000:3000"    
    env_file:
      - .env

    restart: unless-stopped

  pocketbase: #db
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data  
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  reverse-proxy: #caddy
    container_name: caddy-service
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

    
